version: '3.8'
services:  
  db:
    image: postgres:13.5-alpine3.14
    restart: always
    container_name: postgres_db
    environment: 
      POSTGRES_DATABASE: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - 5432:5432
      # 5432